import { UI_SALES_DATA_ACCESS_ARTICLE_UNIT_PROVIDER } from './article-unit';
import { UI_SALES_DATA_ACCESS_INVOICE_PROVIDER } from './invoice';
import { UI_SALES_DATA_ACCESS_CURRENCY_PROVIDER } from './currency';
import { UI_SALES_DATA_ACCESS_VAT_PROVIDER } from './vat';
import { UI_SALES_DATA_ACCESS_COUNTRY_PROVIDER } from './country';
import { UI_SALES_DATA_ACCESS_INVOICE_TYPE_PROVIDER } from './invoice-type';
import { UI_SALES_DATA_ACCESS_CONTRACT_PROVIDER } from './contract';

/** Provides all services for accessing data for the sales-service. */
export const UI_SALES_DATA_ACCESS_SERVICE_PROVIDERS = [
  ...UI_SALES_DATA_ACCESS_ARTICLE_UNIT_PROVIDER,
  ...UI_SALES_DATA_ACCESS_INVOICE_PROVIDER,
  ...UI_SALES_DATA_ACCESS_CURRENCY_PROVIDER,
  ...UI_SALES_DATA_ACCESS_VAT_PROVIDER,
  ...UI_SALES_DATA_ACCESS_COUNTRY_PROVIDER,
  ...UI_SALES_DATA_ACCESS_INVOICE_TYPE_PROVIDER,
  ...UI_SALES_DATA_ACCESS_CONTRACT_PROVIDER,
];
